# Shipment data set from a kaggel

 Data is all about to predict the product got reached on time are not to the coustmor  by using the Randomforesclassfier techniq 

requried Librarys are pandas,numpy,sklearn

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn 

In [12]:
data = pd.read_csv("C:\\Users\\LDA\\Class Data\\shipments.csv") # loading a data set by using the read_csv function
data.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [47]:
data1 = data.drop(["ID"],axis=1) # droping the id column which not necessary to model

In [48]:
data1.head() # seeing the top 5 rows of data

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0               D           Flight                    4                2   
1               F           Flight                    4                5   
2               A           Flight                    2                2   
3               B           Flight                    3                3   
4               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [66]:
# applying the dummies for cat variable by using get_dummies func
ship = pd.get_dummies(data1,columns=["Warehouse_block","Mode_of_Shipment","Gender","Product_importance"],drop_first=True)
ship.head()  

Customer_care_calls  Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                    4                2                  177                3   
1                    4                5                  216                2   
2                    2                2                  183                4   
3                    3                3                  176                4   
4                    2                2                  184                3   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  Warehouse_block_B  \
0                44           1233                    1                  0   
1                59           3088                    1                  0   
2                48           3374                    1                  0   
3                10           1177                    1                  1   
4                46           2484                    1                  0   

   Warehouse_block_C  Warehouse_block_D  Warehouse_block_F  \
0                  0                  1                  0   
1                  0                  0                  1   
2                  0                  0                  0   
3                  0                  0                  0   
4                  1                  0                  0   

   Mode_of_Shipment_Road  Mode_of_Shipment_Ship  Gender_M  \
0                      0                      0         0   
1                      0                      0         1   
2                      0                      0         1   
3                      0                      0         1   
4                      0                      0         0   

   Product_importance_low  Product_importance_medium  
0                       1                          0  
1                       1                          0  
2                       1                          0  
3                       0                          1  
4                       0                          1

In [ ]:
# distributing the data dependent and indepemndent 

In [75]:
X = ship.drop(["Reached.on.Time_Y.N"],axis=1).values
X

array([[  4,   2, 177, ...,   0,   1,   0],
       [  4,   5, 216, ...,   1,   1,   0],
       [  2,   2, 183, ...,   1,   1,   0],
       ...,
       [  5,   4, 242, ...,   0,   1,   0],
       [  5,   2, 223, ...,   1,   0,   1],
       [  2,   5, 155, ...,   0,   1,   0]], dtype=int64)

In [77]:
# spliting the data to dependent variable 
Y = ship["Reached.on.Time_Y.N"].values
Y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [73]:
# importing the library for train test split
from sklearn.model_selection import train_test_split

In [80]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,train_size=0.7,random_state = 50)

In [81]:
# preprocessing the data for standardscaler
from sklearn.preprocessing import StandardScaler  

In [82]:
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.fit_transform(x_test)

In [86]:
# model deployment
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [151]:
# applying ensemble technique
model = RandomForestClassifier(criterion = "entropy",max_depth = 5)
model

RandomForestClassifier(criterion='entropy', max_depth=5)

In [152]:
# training a model 
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=5)

In [153]:
# prediction for x_train data
x_pred= model.predict(x_train)
x_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [154]:
# prediction for x_test data
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [155]:
# checking the accury for training data
model.score(x_train,y_train)

0.7011300168853097

In [156]:
# checking the accuracy for test data / new data
model.score(x_test,y_test)

0.6721212121212121

In [157]:
# applying confusion metrix on test data
confusion_matrix(y_test,y_pred)

array([[1125,  221],
       [ 861, 1093]], dtype=int64)

In [158]:
# applying the confusion metrix to check the tp,fp,tn,fn on train data
confusion_matrix(y_train,x_pred)

array([[2716,  374],
       [1927, 2682]], dtype=int64)